### PR TITLE
added files and folders for our initial-ish commit

### PR DESCRIPTION
**Pull request by Iandonmorgan**
1. git fetch --all
2. git checkout lm-allfiles
3. confirm directories were created: 
 - src
 - src/images
 - src/styles
 - src/scripts
4. confirm files were created: 
 - .gitignore
 - src/index.html
 - src/career.html
 - src/personal.html
 - src/newsFeed.html
 - src/styles/style.css

### CODE REVIEW

**Comment by HalcyonVagabond** [comment]
Great job! Can you plz add a images directory in src? Thank you.

**Comment by Iandonmorgan** [comment]
@HalcyonVagabond Will do!

**Comment by Iandonmorgan** [comment]
I will close this request and resubmit with updated request.

**Comment by Iandonmorgan** [comment]
1. git fetch --all
2. git checkout lm-allfiles
3. confirm directories were created:
- src
- src/images
- src/styles
- src/scripts

4. confirm files were created:
- .gitignore
- src/index.html
- src/career.html
- src/personal.html
- src/newsFeed.html
- src/styles/style.css

**Comment by Iandonmorgan** [comment]
Standby... adding files to src/scripts & src/images

**Comment by Iandonmorgan** [comment]
1. git fetch --all
2. git checkout lm-allfiles
3. confirm directories were created:
 - src
 - src/images
 - src/styles
 - src/scripts

4. confirm files were created/added:
 - .gitignore
 - src/index.html
 - src/career.html
 - src/personal.html
 - src/newsFeed.html
 - src/styles/style.css
 - src/scripts/scripts.js
 - src/images/keanu.jpg

**Comment by Iandonmorgan** [comment]
Three thumbs ups, merging pull request now. Bonus points to Matthew for figuring out that we all needed to do a 'git pull' from the branch lm-allfiles to see the updated files, because 'fetch --all' will only grab the files from the first fetch.

**Pull request merged**
