### PR TITLE
Lm html

### PR DESCRIPTION
**Pull request by Iandonmorgan**
Updated index.html file and style.css with home page additions and formatting

1. git fetch --all
2. git checkout lm-html
3. Let me know what you think!

### CODE REVIEW

**Comment by HalcyonVagabond** [comment]
Hello good sir!
the id on the div tag for the nav bar says "navContainter" instead of "navContainer"
Other that it looks great!

**Comment by mKroogz** [comment]
Same thing Jeremy said.  Looks awesome outside of one minor typo. :)

**Comment by Iandonmorgan** [comment]
haha navContainter fixed to navContainer. git pull from lm-html branch and let me know if you see it. If so, I'll merge with master. Thanks, guys!
-Landon

**Comment by mKroogz** [comment]
Awesome!  You're good from my end!

**Comment by Iandonmorgan** [comment]
Given everyone has reviewed, and the last update was minor, I'll merge this pull request now. Thanks all!

**Pull request merged**
