### PR TITLE
formatting of index, clean-up of styles to use classes

### PR DESCRIPTION
**Pull request by Iandonmorgan**
1. git fetch --all
2. git checkout lm-html2
3. Let me know what you think. I got rid of my global tags in style.css, and played around with formatting on index.html.

### CODE REVIEW

**Comment by mKroogz** [comment]
Test review

**Comment by RockMurdock** [comment]
looks good

**Review by HalcyonVagabond — APPROVED** [review]
Looks good!

**Review by mKroogz — APPROVED** [review]
Looks good

**Review by RockMurdock — APPROVED** [review]
looks good

**Pull request merged**
